export const PROJECT = {
  name: 'V&A Broadbeach',
  number: 'QBM00016',
  description: 'Mechanical Services · East & West Tower + Podiums + Basement',
  lastMeeting: '1 Jun 2026',
  attendees: 'DD, BK, AH',
}

export const STATUSES = ['Not Started', 'In Progress', 'Under Review', 'Complete']

export const STATUS_COLORS = {
  'Not Started': '#888780',
  'In Progress': '#EF9F27',
  'Under Review': '#378ADD',
  'Complete': '#639922',
}

export const CATEGORY_STYLES = {
  Drawing:    { bg: '#E6F1FB', color: '#0C447C' },
  Submittal:  { bg: '#EEEDFE', color: '#3C3489' },
  RFI:        { bg: '#FAEEDA', color: '#633806' },
  Equipment:  { bg: '#EAF3DE', color: '#27500A' },
  Task:       { bg: '#FAECE7', color: '#712B13' },
  Procurement:{ bg: '#FAECE7', color: '#712B13' },
  'Pre-fab':  { bg: '#EAF3DE', color: '#27500A' },
  Calc:       { bg: '#FBEAF0', color: '#72243E' },
  Schematic:  { bg: '#EEEDFE', color: '#3C3489' },
  Admin:      { bg: '#F1EFE8', color: '#444441' },
  QA:         { bg: '#EAF3DE', color: '#27500A' },
  Safety:     { bg: '#FCEBEB', color: '#A32D2D' },
  Commission: { bg: '#FBEAF0', color: '#72243E' },
  Program:    { bg: '#E6F1FB', color: '#0C447C' },
}

const id = (n) => n

export const INITIAL_DATA = {
  pm: {
    label: 'Project Manager',
    owner: 'DD',
    desc: 'D&C program, procurement, Gate 2',
    color: '#E6F1FB',
    textColor: '#0C447C',
    iconColor: '#185FA5',
    metrics: [
      { label: 'Gate 2 re-price', value: 'Open', sub: 'Final items due 5/6/26', warn: true },
      { label: 'Procurement open', value: '6', sub: 'Fans, dampers, grilles pending' },
      { label: 'Podium IFC', value: 'WIP', sub: 'Internal review in progress', warn: true },
      { label: 'Tower IFC', value: 'Pending', sub: 'Mech/Elec/BMS coord', warn: true },
    ],
    progress: [
      { label: 'Engineering close-out', pct: 90, color: '#7F77DD' },
      { label: 'Drafting IFC issue',    pct: 75, color: '#378ADD' },
      { label: 'Procurement',           pct: 60, color: '#1D9E75' },
      { label: 'Site installation',     pct: 20, color: '#EF9F27' },
      { label: 'Commissioning',         pct: 2,  color: '#888780' },
    ],
    cards: [
      { id: id(1),  title: 'Gate 2 re-price — final items',     status: 'In Progress',   category: 'Program',     owner: 'DD',    due: '5/6/26',  pct: 80, overdue: false },
      { id: id(2),  title: 'Podium update — internal review',   status: 'In Progress',   category: 'Program',     owner: 'DD/BK', due: '',        pct: 60, overdue: false },
      { id: id(3),  title: 'Pipe spools — Podiums',             status: 'In Progress',   category: 'Procurement', owner: 'DD',    due: '5/6/26',  pct: 70, overdue: true  },
      { id: id(4),  title: 'Grilles — pending IFC schedules',   status: 'In Progress',   category: 'Procurement', owner: 'DD',    due: '',        pct: 30, overdue: false },
      { id: id(5),  title: 'Exhaust duct contractor',           status: 'Not Started',   category: 'Procurement', owner: 'DD',    due: 'Post G2', pct: 0,  overdue: false },
      { id: id(6),  title: 'Apartment fans order',              status: 'Not Started',   category: 'Procurement', owner: 'DD',    due: 'Post G2', pct: 0,  overdue: false },
      { id: id(7),  title: 'Commissioning plan',                status: 'Not Started',   category: 'Commission',  owner: 'PC',    due: 'Post ENG/DFT', pct: 0, overdue: false },
      { id: id(8),  title: 'Dampers — pending IFC schedules',   status: 'Under Review',  category: 'Procurement', owner: 'DD',    due: '',        pct: 40, overdue: false },
      { id: id(9),  title: 'PMJ cost review',                   status: 'Under Review',  category: 'Task',        owner: 'DD',    due: '',        pct: 55, overdue: false },
      { id: id(10), title: 'Temp cooling — basement',           status: 'Under Review',  category: 'Task',        owner: 'DD',    due: '',        pct: 50, overdue: false },
      { id: id(11), title: 'CHW pumps ordered',                 status: 'Complete',      category: 'Procurement', owner: 'DD',    due: 'Jun 25',  pct: 100, overdue: false },
      { id: id(12), title: 'Hydronic equipment ordered',        status: 'Complete',      category: 'Procurement', owner: 'DD',    due: 'Jun 25',  pct: 100, overdue: false },
      { id: id(13), title: 'Fans & attenuators ordered',        status: 'Complete',      category: 'Procurement', owner: 'DD',    due: 'Jul 25',  pct: 100, overdue: false },
    ],
  },
  eng: {
    label: 'Engineering',
    owner: 'BK',
    desc: 'Calcs, submittals, schematics',
    color: '#EEEDFE',
    textColor: '#3C3489',
    iconColor: '#534AB7',
    metrics: [
      { label: 'Hours used', value: '1264', sub: 'Target: 1129 — 112% over', warn: true },
      { label: 'Hrs to complete', value: '48', sub: 'Forecast final: 117%' },
      { label: 'Tech subs open', value: '4', sub: 'BMS, AHU, DX, MSSB', warn: true },
      { label: 'Schematics', value: 'WIP', sub: 'CHW update needed' },
    ],
    progress: [
      { label: 'Target hours',   pct: 100, color: '#639922' },
      { label: 'Hours used',     pct: 100, color: '#E24B4A' },
      { label: 'Hrs to complete', pct: 15, color: '#EF9F27' },
    ],
    cards: [
      { id: id(20), title: 'BMS tech subs — ongoing',                 status: 'In Progress',  category: 'Submittal', owner: 'BK', due: '',         pct: 65, overdue: true  },
      { id: id(21), title: 'Review Mech/Elec info for MSSB drawings', status: 'In Progress',  category: 'Drawing',   owner: 'BK', due: '5/6/26',   pct: 50, overdue: false },
      { id: id(22), title: 'Review schematic for drafting',           status: 'In Progress',  category: 'Schematic', owner: 'BK', due: '',         pct: 70, overdue: false },
      { id: id(23), title: 'CHW schematics update',                   status: 'In Progress',  category: 'Schematic', owner: 'BK', due: '',         pct: 45, overdue: false },
      { id: id(24), title: 'Commissioning control logic',             status: 'Not Started',  category: 'Calc',      owner: 'BK', due: 'Post site', pct: 0, overdue: false },
      { id: id(25), title: 'Roof plantroom — final review',           status: 'Not Started',  category: 'Calc',      owner: 'BK', due: '',         pct: 0,  overdue: false },
      { id: id(26), title: 'Pipe anchor design — risers',             status: 'Not Started',  category: 'Calc',      owner: 'BK', due: '',         pct: 0,  overdue: false },
      { id: id(27), title: 'AHU tech submission — Daikin resubmit',   status: 'Under Review', category: 'Submittal', owner: 'BK', due: '',         pct: 85, overdue: false },
      { id: id(28), title: 'Fire matrix — submitted',                 status: 'Under Review', category: 'Calc',      owner: 'BK', due: '',         pct: 90, overdue: false },
      { id: id(29), title: 'Pipe insulation schedule — detail sheet', status: 'Under Review', category: 'Calc',      owner: 'BK', due: '',         pct: 80, overdue: false },
      { id: id(30), title: 'Recreation areas — East Tower',           status: 'Complete',     category: 'Calc',      owner: 'BK', due: '',         pct: 100, overdue: false },
      { id: id(31), title: 'DE-001 detail sheet IFC confirmed',       status: 'Complete',     category: 'Drawing',   owner: 'BK', due: '',         pct: 100, overdue: false },
      { id: id(32), title: 'Acoustic pressure break submitted',       status: 'Complete',     category: 'Submittal', owner: 'BK', due: '',         pct: 100, overdue: false },
    ],
  },
  draft: {
    label: 'Drafting',
    owner: 'AH',
    desc: 'DSR, IFC drawings, coordination',
    color: '#EAF3DE',
    textColor: '#27500A',
    iconColor: '#3B6D11',
    metrics: [
      { label: 'Hours used', value: '5062', sub: 'Target: 3694 — over budget', warn: true },
      { label: 'Hrs to complete', value: '182', sub: 'Forecast final: 94%' },
      { label: 'In coordination', value: '6', sub: 'Tower + basement dwgs', warn: true },
      { label: 'DRS status', value: 'Update', sub: 'Needed this week' },
    ],
    progress: [
      { label: 'Basement',              pct: 85, color: '#7F77DD' },
      { label: 'Podium L1–L4',          pct: 80, color: '#378ADD' },
      { label: 'East tower apartments', pct: 75, color: '#1D9E75' },
      { label: 'West tower apartments', pct: 70, color: '#EF9F27' },
      { label: 'Rec areas & penthouses',pct: 55, color: '#D85A30' },
      { label: 'Roof plantrooms',       pct: 40, color: '#888780' },
    ],
    cards: [
      { id: id(40), title: 'West tower pipe & BW layouts',         status: 'In Progress',  category: 'Drawing', owner: 'AH', due: '',       pct: 70, overdue: true  },
      { id: id(41), title: 'East & West top tower layouts',        status: 'In Progress',  category: 'Drawing', owner: 'AH', due: '',       pct: 65, overdue: true  },
      { id: id(42), title: 'Level 3 pipe spools — AR updating',   status: 'In Progress',  category: 'Drawing', owner: 'AR', due: '1/6/26', pct: 80, overdue: false },
      { id: id(43), title: 'Level 4 CPEX fan room update',        status: 'In Progress',  category: 'Drawing', owner: 'AH', due: '1/6/26', pct: 55, overdue: false },
      { id: id(44), title: 'Pressure break — PM/ENG review',      status: 'In Progress',  category: 'Drawing', owner: 'AH', due: '',       pct: 60, overdue: false },
      { id: id(45), title: 'ACC asset markup',                     status: 'Not Started',  category: 'Drawing', owner: 'NS', due: '',       pct: 0,  overdue: false },
      { id: id(46), title: 'Basement fire dampers',                status: 'Not Started',  category: 'Drawing', owner: 'AH', due: '',       pct: 0,  overdue: false },
      { id: id(47), title: 'Update schematics — D&E format',      status: 'Not Started',  category: 'Drawing', owner: 'AR', due: '',       pct: 0,  overdue: false },
      { id: id(48), title: 'East Tower apartments — peer review',  status: 'Under Review', category: 'Drawing', owner: 'AH', due: '',       pct: 90, overdue: false },
      { id: id(49), title: 'West Tower apartments — peer review',  status: 'Under Review', category: 'Drawing', owner: 'AH', due: '',       pct: 88, overdue: false },
      { id: id(50), title: 'Podium L1–L2 drawings',               status: 'Under Review', category: 'Drawing', owner: 'AH', due: '',       pct: 85, overdue: false },
      { id: id(51), title: 'East Tower IFC — issued for peer review', status: 'Complete', category: 'Drawing', owner: 'AH', due: '17/3/26', pct: 100, overdue: false },
      { id: id(52), title: 'West Tower IFC — issued for peer review', status: 'Complete', category: 'Drawing', owner: 'AH', due: '17/3/26', pct: 100, overdue: false },
      { id: id(53), title: 'Podium L1–L2 IFA issued',             status: 'Complete',     category: 'Drawing', owner: 'AH', due: 'Mar 26', pct: 100, overdue: false },
    ],
  },
  site: {
    label: 'Site',
    owner: 'WW/AS',
    desc: 'Labour, WBS, QA, ITPs',
    color: '#FAECE7',
    textColor: '#712B13',
    iconColor: '#993C1D',
    metrics: [
      { label: 'Site start', value: 'Active', sub: 'GF/L1 — May 26' },
      { label: 'WBS duct dates', value: 'TBC', sub: 'Review required', warn: true },
      { label: 'ITPs submitted', value: 'Yes', sub: 'D&E MPX format' },
      { label: 'Pre-fab status', value: 'WIP', sub: 'FCU + pump skid', warn: true },
    ],
    progress: [
      { label: 'GF/L1 Sheet 1 & 2',  pct: 40, color: '#EF9F27' },
      { label: 'Basement core duct',  pct: 10, color: '#D85A30' },
      { label: 'Podium L2–L4',        pct: 5,  color: '#888780' },
      { label: 'Tower levels',        pct: 2,  color: '#888780' },
    ],
    cards: [
      { id: id(60), title: 'DRS update — print & email',          status: 'In Progress',  category: 'Admin',    owner: 'WW/DD', due: '',        pct: 50, overdue: true  },
      { id: id(61), title: 'FCU pre-fab planning',                status: 'In Progress',  category: 'Pre-fab',  owner: 'DD/AS', due: '',        pct: 40, overdue: false },
      { id: id(62), title: 'Pump skid frame quote',               status: 'In Progress',  category: 'Pre-fab',  owner: 'DD',    due: '',        pct: 60, overdue: false },
      { id: id(63), title: 'L3 pipe crossover — steel clash',     status: 'In Progress',  category: 'Task',     owner: 'DD',    due: '',        pct: 30, overdue: true  },
      { id: id(64), title: 'Check walls changing on site',        status: 'In Progress',  category: 'Task',     owner: 'DD',    due: '',        pct: 25, overdue: false },
      { id: id(65), title: 'Commissioning plan',                  status: 'Not Started',  category: 'Commission', owner: 'PC',  due: 'Post ENG/DFT', pct: 0, overdue: false },
      { id: id(66), title: 'Steel frame PO',                      status: 'Not Started',  category: 'Pre-fab',  owner: 'DD/AS', due: '',        pct: 0,  overdue: false },
      { id: id(67), title: 'Loss of productivity — IRIS Zone 1',  status: 'Not Started',  category: 'Task',     owner: 'DD',    due: '',        pct: 0,  overdue: false },
      { id: id(68), title: 'Site folder — ACC setup',             status: 'Under Review', category: 'Admin',    owner: 'WW',    due: '',        pct: 80, overdue: false },
      { id: id(69), title: 'Labour tracker — QA by Admin',        status: 'Under Review', category: 'Admin',    owner: 'WW',    due: '',        pct: 90, overdue: false },
      { id: id(70), title: 'Pumps — due EOM to Bris warehouse',   status: 'Under Review', category: 'Pre-fab',  owner: 'DD',    due: 'EOM Jun 26', pct: 75, overdue: false },
      { id: id(71), title: 'ITPs D&E (MPX format) created',      status: 'Complete',     category: 'QA',       owner: 'AS',    due: '',        pct: 100, overdue: false },
      { id: id(72), title: 'Incoming site sheds — B1',            status: 'Complete',     category: 'Task',     owner: 'WW',    due: '',        pct: 100, overdue: false },
      { id: id(73), title: 'SWMS reviewed & signed',              status: 'Complete',     category: 'Safety',   owner: 'AS',    due: '',        pct: 100, overdue: false },
    ],
  },
}
